name: Pylint

on: 
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r fastapi_serving/requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') -d=R,C,W
    - name: Comment on PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
            Looks good. :wave:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
