name: pylint

on: 
  pull_request:
    branches: [master]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          pip install -r fastapi_serving/requirements.txt
          pip install requests --user
          pip install tensorflow==2.3.0
          pip install pylint
    - name: Analysing the code with pylint
      working-directory: ./fastapi_serving
      run: |
        pylint $(git ls-files '*.py') -d=R,C,W || exit 0
    - name: Comment on PR
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Looks good! :wave:'
            })