name: pytest
on: 
  pull_request:
    branches: [master]

jobs:
  run-test-code:
    runs-on: tensorflow/tensorflow:latest-gpu
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6.9"
      - run: pip install -r fastapi_serving/requirements.txt
      - name: Run tests
        working-directory: ./fastapi_serving
        run: pytest