name: pytest
on: 
  pull_request:
    branches: [master]

jobs:
  run-test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6.9"
      - run: |
          pip install -r fastapi_serving/requirements.txt
          pip install requests --user
          pip install numpy
          pip install tensorflow==2.3.0
        
      - name: Run tests
        working-directory: ./fastapi_serving
        run: pytest